/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cat.gltf -o src/components/CatMia.jsx 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function CatMia(props) {
  const { scene } = useGLTF('/models/cat.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.483, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.Character1_Hips} />
        <skinnedMesh geometry={nodes.eye_outL.geometry} material={materials.blinn1} skeleton={nodes.eye_outL.skeleton} />
        <skinnedMesh geometry={nodes.eye_outR.geometry} material={materials.blinn1} skeleton={nodes.eye_outR.skeleton} />
        <skinnedMesh name="EyeL01" geometry={nodes.EyeL01.geometry} material={materials.anisotropic3} skeleton={nodes.EyeL01.skeleton} morphTargetDictionary={nodes.EyeL01.morphTargetDictionary} morphTargetInfluences={nodes.EyeL01.morphTargetInfluences} />
        <skinnedMesh name="EyeR01" geometry={nodes.EyeR01.geometry} material={materials.anisotropic3} skeleton={nodes.EyeR01.skeleton} morphTargetDictionary={nodes.EyeR01.morphTargetDictionary} morphTargetInfluences={nodes.EyeR01.morphTargetInfluences} />
        <skinnedMesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.anisotropic2} skeleton={nodes.Mesh.skeleton} morphTargetDictionary={nodes.Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Mesh.morphTargetInfluences} />
        <skinnedMesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.anisotropic1} skeleton={nodes.Mesh_1.skeleton} morphTargetDictionary={nodes.Mesh_1.morphTargetDictionary} morphTargetInfluences={nodes.Mesh_1.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cat.gltf')
