import React from 'react'
import { useGLTF } from '@react-three/drei'

export function OfficeContact(props) {
  const { nodes, materials } = useGLTF('/models/officeCall.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.413}>
        <mesh geometry={nodes.Object_103373.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103374.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103375.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103376.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103377.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103378.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103379.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103380.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103381.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103382.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103383.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103384.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103385.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103386.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103387.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103388.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103389.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103390.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103391.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_103392.geometry} material={materials.monitor_bar} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.sofa} />
        <mesh geometry={nodes.Object_110001.geometry} material={materials.sofa} />
        <mesh geometry={nodes.Object_110002.geometry} material={materials.sofa} />
        <mesh geometry={nodes.Object_110003.geometry} material={materials.sofa} />
        <mesh geometry={nodes.Object_110005.geometry} material={materials.sofa} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.coffee} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material_41} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.lamba_effaf} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['paper.003']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['paper.004']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['paper.005']} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.None} />
        <mesh geometry={nodes.Object_64.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64001.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64002.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64003.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64004.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64005.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64077.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64078.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64079.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64080.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64081.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_64082.geometry} material={materials['book.003']} />
        <mesh geometry={nodes.Object_70174.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70175.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70176.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70177.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70178.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70179.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70180.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70181.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70182.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70183.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70184.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70185.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70186.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70187.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70188.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70189.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70190.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70191.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70192.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70193.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70194.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70195.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70196.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70197.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70198.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70199.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70200.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70201.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70202.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70203.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70204.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70205.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70206.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70207.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70208.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70209.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70210.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70211.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70212.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70213.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70214.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70215.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70216.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70217.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70218.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70219.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70220.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70221.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70222.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70223.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70224.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70225.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70226.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70227.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70228.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70229.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70230.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70231.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70232.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70233.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70234.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70235.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70236.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70237.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70238.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70239.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70240.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70241.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70242.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70243.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70244.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70245.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70246.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70247.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70248.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70249.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70250.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70251.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70252.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70253.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70254.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70255.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70256.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70257.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70258.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_70259.geometry} material={materials.book_inside} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.coffee_table} />
        <mesh geometry={nodes.Object_98.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98001.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98002.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98003.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98004.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98005.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98006.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98007.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98008.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98009.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98010.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98011.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98012.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98013.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98014.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98015.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98016.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98017.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98018.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98019.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98020.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98021.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98022.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98023.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98024.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98025.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98026.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98027.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98028.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98029.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98030.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98031.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98032.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98033.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98034.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98035.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98036.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98037.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98038.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98039.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98040.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98041.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98042.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98043.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98044.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98045.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98046.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98047.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98048.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98049.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98050.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98051.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98052.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98053.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98054.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98055.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98056.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98057.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98058.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98059.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98060.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98061.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98062.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98063.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98064.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98065.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98066.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98067.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98068.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98069.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98070.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98071.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98072.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98073.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98074.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98075.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98076.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98077.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98272.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98273.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98274.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98275.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98276.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98277.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98278.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98279.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98293.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98294.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98295.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98296.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98297.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98298.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98299.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98300.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98301.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98302.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98303.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98304.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98305.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98306.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98307.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98308.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98309.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98310.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98311.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98312.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98313.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98314.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98315.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98316.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98317.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98318.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98319.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98320.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98321.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98322.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98323.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98324.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98325.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98326.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98327.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98328.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98329.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98330.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98331.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98332.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98333.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98334.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98335.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98336.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98337.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98338.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98339.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98340.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98341.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98342.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98343.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98344.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98345.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98346.geometry} material={materials['lamba.2']} />
        <mesh geometry={nodes.Object_98347.geometry} material={materials['lamba.2']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/officeCall.gltf')
